---
- name: Ensure custom groups are present
  group:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ custom_groups }}"

- name: Ensure users are present
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    state: "{{ item.state }}"
    password: "{{ item.password | password_hash('sha512') }}"
    groups: "{{ item.groups }}"
  loop: "{{ users }}"

- name: Ensure .ssh directory exists for each user
  file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: "0700"
  loop: "{{ users }}"
  when: item.state == 'present'

- name: Generate SSH key pair for each user
  openssh_keypair:
    path: "/home/{{ item.name }}/.ssh/id_rsa"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: "0600"
  loop: "{{ users }}"
  when: item.state == 'present'

- name: Fetch public key to the controller
  fetch:
    src: "/home/{{ item.name }}/.ssh/id_rsa.pub"
    dest: "roles/users/files/id_rsa_{{ item.name }}.pub"
    flat: yes
  loop: "{{ users }}"
  when: item.state == 'present'

- name: Ensure SSH keys are present in authorized_keys
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', 'roles/users/files/id_rsa_{{ item.name }}.pub') }}"
  loop: "{{ users }}"
  when: item.state == 'present'
